// ocaml_4142_opcodes.svh
// Auto/manual translation of OCaml 4.14.2 runtime/caml/instruct.h enum instructions.
// IMPORTANT: opcode numeric values are defined by order. Do not reorder.

`ifndef OCAML_4142_OPCODES_SVH
`define OCAML_4142_OPCODES_SVH

typedef enum logic [7:0] {
  // 0..
  ACC0, ACC1, ACC2, ACC3, ACC4, ACC5, ACC6, ACC7,
  ACC, PUSH,
  PUSHACC0, PUSHACC1, PUSHACC2, PUSHACC3,
  PUSHACC4, PUSHACC5, PUSHACC6, PUSHACC7,
  PUSHACC, POP, ASSIGN,
  ENVACC1, ENVACC2, ENVACC3, ENVACC4, ENVACC,
  PUSHENVACC1, PUSHENVACC2, PUSHENVACC3, PUSHENVACC4, PUSHENVACC,
  PUSH_RETADDR, APPLY, APPLY1, APPLY2, APPLY3,
  APPTERM, APPTERM1, APPTERM2, APPTERM3,
  RETURN, RESTART, GRAB,
  CLOSURE, CLOSUREREC,
  OFFSETCLOSUREM3, OFFSETCLOSURE0, OFFSETCLOSURE3, OFFSETCLOSURE,
  PUSHOFFSETCLOSUREM3, PUSHOFFSETCLOSURE0,
  PUSHOFFSETCLOSURE3, PUSHOFFSETCLOSURE,
  GETGLOBAL, PUSHGETGLOBAL, GETGLOBALFIELD, PUSHGETGLOBALFIELD, SETGLOBAL,
  ATOM0, ATOM, PUSHATOM0, PUSHATOM,
  MAKEBLOCK, MAKEBLOCK1, MAKEBLOCK2, MAKEBLOCK3, MAKEFLOATBLOCK,
  GETFIELD0, GETFIELD1, GETFIELD2, GETFIELD3, GETFIELD, GETFLOATFIELD,
  SETFIELD0, SETFIELD1, SETFIELD2, SETFIELD3, SETFIELD, SETFLOATFIELD,
  VECTLENGTH, GETVECTITEM, SETVECTITEM,
  GETBYTESCHAR, SETBYTESCHAR,
  BRANCH, BRANCHIF, BRANCHIFNOT, SWITCH, BOOLNOT,
  PUSHTRAP, POPTRAP, RAISE,
  CHECK_SIGNALS,
  C_CALL1, C_CALL2, C_CALL3, C_CALL4, C_CALL5, C_CALLN,
  CONST0, CONST1, CONST2, CONST3, CONSTINT,
  PUSHCONST0, PUSHCONST1, PUSHCONST2, PUSHCONST3, PUSHCONSTINT,
  NEGINT, ADDINT, SUBINT, MULINT, DIVINT, MODINT,
  ANDINT, ORINT, XORINT, LSLINT, LSRINT, ASRINT,
  EQ, NEQ, LTINT, LEINT, GTINT, GEINT,
  OFFSETINT, OFFSETREF, ISINT,
  GETMETHOD,
  BEQ, BNEQ, BLTINT, BLEINT, BGTINT, BGEINT,
  ULTINT, UGEINT,
  BULTINT, BUGEINT,
  GETPUBMET, GETDYNMET,
  STOP,
  EVENT, BREAK,
  RERAISE, RAISE_NOTRACE,
  GETSTRINGCHAR
} opcode_t;

// Quick sanity: FIRST_UNIMPLEMENTED_OP is one past GETSTRINGCHAR in C.
// If you want it, keep it separate:
localparam int unsigned FIRST_UNIMPLEMENTED_OP = int'(GETSTRINGCHAR) + 1;

// --- Immediate classification helpers ---
// These functions let your FETCH stage decide whether to fetch 0/1/2 immediates.
// For a minimal bring-up, you can start with only imm8 and add imm16 later.

function automatic bit opcode_has_imm8(opcode_t op);
  unique case (op)
    // 1-byte immediates
    ACC, PUSHACC, POP, ASSIGN,
    ENVACC, PUSHENVACC,
    PUSH_RETADDR,
    APPLY, APPTERM, RETURN, GRAB,
    OFFSETCLOSURE, PUSHOFFSETCLOSURE,
    GETGLOBAL, PUSHGETGLOBAL, SETGLOBAL,
    ATOM, PUSHATOM,
    MAKEBLOCK, GETFIELD, SETFIELD,
    VECTLENGTH, GETVECTITEM, SETVECTITEM,
    GETBYTESCHAR, SETBYTESCHAR,
    BRANCH, BRANCHIF, BRANCHIFNOT, BOOLNOT,
    C_CALLN,
    CONSTINT, PUSHCONSTINT,
    OFFSETINT, OFFSETREF,
    GETMETHOD,
    BEQ, BNEQ, BLTINT, BLEINT, BGTINT, BGEINT,
    BULTINT, BUGEINT,
    GETPUBMET, GETDYNMET,
    GETSTRINGCHAR
      : opcode_has_imm8 = 1'b1;
    default
      : opcode_has_imm8 = 1'b0;
  endcase
endfunction

function automatic bit opcode_has_imm16(opcode_t op);
  unique case (op)
    // SWITCH uses 16-bit/word-sized tables in real OCaml; treat as special.
    SWITCH: opcode_has_imm16 = 1'b1;
    default: opcode_has_imm16 = 1'b0;
  endcase
endfunction

`endif // OCAML_4142_OPCODES_SVH
