// VC707 harness for the OCaml 4.14 bytecode VM (ocaml4142_vm_rtl).
//
// Runs the program in the code ROM once after configuration (and again on
// each CPU_RESET press), sending to the USB UART (115200 8N1):
//   a banner, the program's caml_ml_output_char output, and a report
//   "== halt pc=... accu=... cycles=... ==" when it stops (or "== PC!! ..."
//   if the pc leaves the program).
//
// LEDs: 0 heartbeat, 1 MMCM locked, 2 running, 3 halted, 4 pc out of range,
//       5 output FIFO overflowed, 6 output pending, 7 CPU_RESET held.

`include "program.vh"  // PROGRAM_HEX, PROGRAM_WORDS, HEAP_WORDS: generated by gen.sh

module vc707_vm_top (
    input        clk200_p,
    input        clk200_n,
    input        cpu_reset,
    output       serial_tx,
    output [7:0] leds
);
  localparam CLK_HZ = 25_000_000;  // MMCM: 200 MHz * 5 / 40
  localparam BAUD = 115200;

  // ---------------------------------------------------------------- clocking
  wire clk200, mmcm_fb, clk_mmcm, locked, clk;
  IBUFDS clk200_buf (.I(clk200_p), .IB(clk200_n), .O(clk200));
  MMCME2_ADV #(
      .BANDWIDTH       ("OPTIMIZED"),
      .CLKFBOUT_MULT_F (5),
      .CLKIN1_PERIOD   (5.0),
      .CLKOUT0_DIVIDE_F(40),
      .CLKOUT0_PHASE   (0),
      .DIVCLK_DIVIDE   (1),
      .REF_JITTER1     (0.01)
  ) mmcm (
      .CLKFBIN (mmcm_fb),
      .CLKIN1  (clk200),
      .PWRDWN  (1'b0),
      .RST     (cpu_reset),
      .CLKFBOUT(mmcm_fb),
      .CLKOUT0 (clk_mmcm),
      .LOCKED  (locked)
  );
  BUFG clk_buf (.I(clk_mmcm), .O(clk));

  // Reset held until the MMCM has been locked for 2^16 cycles.
  reg [1:0] locked_sync = 2'b00;
  reg [16:0] por = 17'd0;
  wire rst = !por[16];
  always @(posedge clk) begin
    locked_sync <= {locked_sync[0], locked};
    if (!locked_sync[1]) por <= 17'd0;
    else if (rst) por <= por + 17'd1;
  end

  // ---------------------------------------------------------------- the VM
  wire [23:0] pc;
  wire [31:0] accu;
  wire        halted, putc_valid;
  wire [ 7:0] putc_char;
  reg         vm_rst;

  // Code ROM: asynchronous, as the VM samples code_rdata in the cycle it
  // presents pc (the testbench's code_rom[pc]).
  reg  [31:0] code_rom [0:`PROGRAM_WORDS-1];
  initial $readmemh(`PROGRAM_HEX, code_rom);
  wire        pc_in_program = (pc < `PROGRAM_WORDS);
  wire        pc_escaped_now = (pc > `PROGRAM_WORDS);  // pc == end right after fetching a final STOP
  wire [31:0] code_rdata = pc_in_program ? code_rom[pc] : 32'hDEADBEEF;

  // 32K-word stack and heap: at most one RAMB36 per bit, so no cascaded
  // RAMB36 pairs, which nextpnr's xilinx packer does not yet keep together.
  ocaml4142_vm_rtl #(
      .STACK_AW       (15),
      .HEAP_AW        (15),
      .HEAP_INIT      ("heap.hex"),     // the program's constants (gen.sh)
      .GLOBALS_INIT   ("globals.hex"),
      .HEAP_INIT_WORDS(`HEAP_WORDS)
  ) vm (
      .clk        (clk),
      .reset      (vm_rst),
      .pc         (pc),
      .code_rdata (code_rdata),
      .trap_ready (1'b0),
      .trap_result(32'd0),
      .accu       (accu),
      .halted     (halted),
      .putc_valid (putc_valid),
      .putc_char  (putc_char)
  );

  // ------------------------------------------------- messages and sequencing
  function [63:0] hex32(input [31:0] v);
    integer i;
    reg [3:0] n;
    begin
      for (i = 0; i < 8; i = i + 1) begin
        n = v[4*i+:4];
        hex32[8*i+:8] = (n < 10) ? ("0" + n) : ("a" + n - 10);
      end
    end
  endfunction

  localparam BANNER = "\r\n== OCaml bytecode VM on VC707 ==\r\n";
  localparam BANNER_LEN = 36;
  localparam REPORT_LEN = 56;  // "\r\n== halt pc=........ accu=........ cycles=........ ==\r\n"
  localparam MSG_MAX = (BANNER_LEN > REPORT_LEN) ? BANNER_LEN : REPORT_LEN;

  localparam S_BANNER = 2'd0, S_RUN = 2'd1, S_REPORT = 2'd2, S_IDLE = 2'd3;
  reg [1:0] phase;
  reg [8*MSG_MAX-1:0] msg;  // next character in the top byte
  reg [6:0] msg_left;
  reg [31:0] cycles;
  reg pc_escaped, fifo_overflow;

  // Output FIFO feeding the UART (the VM does not wait for it).
  reg [7:0] fifo[0:1023];
  reg [10:0] fifo_wp, fifo_rp;  // one extra bit tells full from empty
  wire fifo_empty = (fifo_wp == fifo_rp);
  wire fifo_full = (fifo_wp[9:0] == fifo_rp[9:0]) && (fifo_wp[10] != fifo_rp[10]);
  reg fifo_push;
  reg [7:0] fifo_din;

  wire sending_msg = (phase == S_BANNER || phase == S_REPORT) && msg_left != 0;
  wire vm_stopped = halted || pc_escaped_now;

  always @(*) begin
    fifo_push = 1'b0;
    fifo_din  = 8'd0;
    if (sending_msg && !fifo_full) begin
      fifo_push = 1'b1;
      fifo_din  = msg[8*MSG_MAX-1-:8];
    end else if (phase == S_RUN && putc_valid) begin
      fifo_push = !fifo_full;
      fifo_din  = putc_char;
    end
  end

  always @(posedge clk) begin
    if (rst) begin
      phase <= S_BANNER;
      msg <= {BANNER, {(MSG_MAX - BANNER_LEN) {8'h00}}};
      msg_left <= BANNER_LEN;
      vm_rst <= 1'b1;
      cycles <= 32'd0;
      pc_escaped <= 1'b0;
      fifo_overflow <= 1'b0;
    end else begin
      if (sending_msg && !fifo_full) begin
        msg <= msg << 8;
        msg_left <= msg_left - 7'd1;
      end
      if (phase == S_RUN && putc_valid && fifo_full) fifo_overflow <= 1'b1;
      case (phase)
        S_BANNER:
        if (msg_left == 0) begin
          vm_rst <= 1'b0;
          phase  <= S_RUN;
        end
        S_RUN: begin
          cycles <= cycles + 32'd1;
          if (vm_stopped) begin
            vm_rst <= 1'b1;
            pc_escaped <= !halted;
            msg <= {"\r\n== ", halted ? "halt" : "PC!!", " pc=", hex32({8'd0, pc}),
                    " accu=", hex32(accu), " cycles=", hex32(cycles), " ==\r\n",
                    {(MSG_MAX - REPORT_LEN) {8'h00}}};
            msg_left <= REPORT_LEN;
            phase <= S_REPORT;
          end
        end
        S_REPORT: if (msg_left == 0) phase <= S_IDLE;
        default: ;
      endcase
    end
  end

  always @(posedge clk) if (fifo_push) fifo[fifo_wp[9:0]] <= fifo_din;

  // ---------------------------------------------------------------- UART TX
  // picosoc's simpleuart (from xc7-bitstream-tools examples/vc707-ethmin),
  // fed from the FIFO: a byte goes when reg_dat_we is high and it isn't waiting.
  reg [7:0] fifo_q;
  reg fifo_q_valid;
  wire uart_wait;
  wire uart_takes_byte = fifo_q_valid && !uart_wait;
  wire fifo_pop = !fifo_q_valid && !fifo_empty;

  simpleuart #(.DEFAULT_DIV(CLK_HZ / BAUD)) uart (
      .clk         (clk),
      .resetn      (!rst),
      .ser_tx      (serial_tx),
      .ser_rx      (1'b1),
      .reg_div_we  (4'b0000),
      .reg_div_di  (32'd0),
      .reg_div_do  (),
      .reg_dat_we  (fifo_q_valid),
      .reg_dat_re  (1'b0),
      .reg_dat_di  ({24'd0, fifo_q}),
      .reg_dat_do  (),
      .reg_dat_wait(uart_wait)
  );

  always @(posedge clk) begin
    if (rst) begin
      fifo_wp <= 11'd0;
      fifo_rp <= 11'd0;
      fifo_q_valid <= 1'b0;
    end else begin
      if (fifo_push) fifo_wp <= fifo_wp + 11'd1;
      if (fifo_pop) begin  // synchronous read: the byte is in fifo_q next cycle
        fifo_rp <= fifo_rp + 11'd1;
        fifo_q_valid <= 1'b1;
      end else if (uart_takes_byte) fifo_q_valid <= 1'b0;
    end
  end
  always @(posedge clk) if (fifo_pop) fifo_q <= fifo[fifo_rp[9:0]];

  // ---------------------------------------------------------------- LEDs
  reg [24:0] heartbeat = 25'd0;
  always @(posedge clk) heartbeat <= heartbeat + 25'd1;
  assign leds = {cpu_reset, fifo_q_valid || !fifo_empty, fifo_overflow, pc_escaped,
                 phase == S_IDLE && !pc_escaped, phase == S_RUN, locked, heartbeat[24]};
endmodule
