#!/usr/bin/env python3
"""gen_rom_bram.py program.hex out.v [module] -- a ROM as explicit x1 block RAMs.

yosys slices a 32-bit ROM into RAMB36s at x9 because that uses the fewest of
them, and a RAMB36 at x9 loses its ninth bit in the open flow: the parity bit
comes out of the lower RAMB18's wire, which prjxray's site-pin mapping does
not model.  Every ninth bit of the program and its constants was wrong, which
is what made the netbooted VM print garbage and send frames with a MAC of
ASCII text.

Inference cannot be told which width to use, so the ROM is written out as one
RAMB36E1 per bit, each 32K deep at x1 -- the mode the open flow gets right,
verified on hardware by fpga/bramtest.  The contents become INIT parameters
here rather than a $readmemh at elaboration.

The generated module reads synchronously on port A, which is what the VM's
fetch unit expects: present the address, take the word the cycle after.
"""
import sys

DEPTH = 32768          # one RAMB36 at x1
INIT_LINES = 128       # 128 * 256 bits = 32768
BITS_PER_LINE = 256


def read_hex(path):
    words = []
    for line in open(path):
        line = line.split('//')[0].strip()
        if line:
            words.append(int(line, 16))
    return words


def init_params(bit, words):
    """INIT_00..INIT_7F for one bit slice: address a is bit a of the stream."""
    out = []
    for ln in range(INIT_LINES):
        v = 0
        for j in range(BITS_PER_LINE):
            a = ln * BITS_PER_LINE + j
            if a < len(words) and (words[a] >> bit) & 1:
                v |= 1 << j
        if v:
            out.append(f".INIT_{ln:02X}(256'h{v:064x})")
    return out


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    hexfile, outfile = sys.argv[1], sys.argv[2]
    module = sys.argv[3] if len(sys.argv) > 3 else "code_rom_bram"
    words = read_hex(hexfile)
    if len(words) > DEPTH:
        sys.exit(f"{hexfile}: {len(words)} words, more than the {DEPTH} one x1 RAMB36 holds")
    width = 32

    o = [f"// Generated by tools/gen_rom_bram.py from {hexfile} ({len(words)} words).",
         "// One RAMB36E1 per bit, 32K deep at x1 -- see the script for why the",
         "// width is pinned rather than inferred.  Do not edit.",
         "`default_nettype none",
         f"module {module} (",
         "\tinput  wire        clk,",
         "\tinput  wire        en,",
         "\tinput  wire [14:0] addr,",
         f"\toutput wire [{width-1}:0] dout",
         ");"]
    for bit in range(width):
        params = ", ".join([".READ_WIDTH_A(1)", ".READ_WIDTH_B(1)",
                            ".WRITE_WIDTH_A(1)", ".WRITE_WIDTH_B(1)",
                            '.RAM_MODE("TDP")', ".DOA_REG(0)", ".DOB_REG(0)",
                            '.SIM_DEVICE("7SERIES")'] + init_params(bit, words))
        o.append(f"\tRAMB36E1 #({params}) b{bit} (")
        o.append("\t\t.CLKARDCLK(clk), .CLKBWRCLK(clk),")
        o.append("\t\t.ENARDEN(en), .ENBWREN(1'b0),")
        o.append("\t\t.REGCEAREGCE(1'b0), .REGCEB(1'b0),")
        o.append("\t\t.RSTRAMARSTRAM(1'b0), .RSTRAMB(1'b0),")
        o.append("\t\t.RSTREGARSTREG(1'b0), .RSTREGB(1'b0),")
        o.append("\t\t.ADDRARDADDR({1'b0, addr}), .ADDRBWRADDR(16'b0),")
        o.append("\t\t.DIADI(32'b0), .DIPADIP(4'b0), .DIBDI(32'b0), .DIPBDIP(4'b0),")
        o.append("\t\t.WEA(4'b0), .WEBWE(8'b0),")
        o.append(f"\t\t.DOADO(dout_bit{bit}), .DOPADOP(), .DOBDO(), .DOPBDOP(),")
        o.append("\t\t.CASCADEINA(1'b0), .CASCADEINB(1'b0), .CASCADEOUTA(), .CASCADEOUTB(),")
        o.append("\t\t.INJECTDBITERR(1'b0), .INJECTSBITERR(1'b0),")
        o.append("\t\t.DBITERR(), .SBITERR(), .ECCPARITY(), .RDADDRECC());")
    # the per-bit output buses, declared after use is fine in Verilog-2005 only
    # for nets, so they are declared up front instead
    decls = [f"\twire [31:0] dout_bit{b};" for b in range(width)]
    o = o[:10] + decls + o[10:]
    o.append("\tassign dout = {" + ", ".join(f"dout_bit{b}[0]" for b in reversed(range(width))) + "};")
    o.append("endmodule")
    o.append("`default_nettype wire")
    open(outfile, "w").write("\n".join(o) + "\n")
    print(f"{outfile}: {width} x1 RAMB36E1, {len(words)} words")


if __name__ == "__main__":
    main()
